import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../util/requests'
import Cover from './Cover'
import { useState } from 'react'

export default function Home({ results }) {

  return (
    <div>
      <Head>
        <title>Netflix by Rahul</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/netfilx.png" />
      </Head>
      <div>
      <Header />
      <Nav />
      <Results results={results} />
      </div>



    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url

    }`).then(res => res.json());

  return {
    props: {
      results: request.results
    }
  }

}